#   Ceci est un code pour créer une ia qui propose des recommandation basé sur les bonnes ou mauvaise réponse d'un questionnaire
#   Pour le cours de philo 2 Cchic
#   Questions basées sur les notes de cours personnelles de météo 1 du CQFA
#
#   Olivier Moreau
#

import streamlit as st

bqhumidité = [
    {"question" : "Quel est l'élément le plus important en météo?", "réponse" : "la vapeur d'eau"},
    {"question" : "Le point de rosée augmente si l'air est...", "réponse" : "chaud"},
    {"question" : "Qu'est ce que le point de rosée?", "réponse" : "La température à pression constante à laquelle si l'air doit être refroidit pour qu'il y ait saturation"},
    {"question" : "Que fait l'eau lorsqu'elle est dans l'air et devient liquide?", "réponse" : "elle donne son énergie à l'air, ce qui augmente la température de l'air"},
]

bqréchauffement = [
    {"question" : "Quel est la température qui définit la tropopause?", "réponse" : "-56"},
    {"question" : "Quels sont les quatres couches de l'atmosphère?", "réponse" : "la troposphère, la mésosphère, la stratosphère et la thermoshère"},
    {"question" : "Quel type d'onde nous envoit le Soleil (2 lettres) et quel est sa longeur d'onde?", "réponse" : "uv et petite ou courte"},
    {"question" : "Qu'est ce que la réflexion Albédo?", "réponse" : "Lorsque les rayons touchent la terre perpendiculairement, ils sont plus puissant que ceux tengent"},
]

bqrefroidissement = [
    {"question" : "Comment ce nomme le concept qui définit que la température diminue de 1,98°C par 1000 pi?", "réponse" : "le gradient thermique verticale"},
    {"question" : "Comment ce nomme le concept qui définit que la température diminue de 3°C par 1000 pi?", "réponse" : "le gradient adiabatique sec"},
]

stabilite_air = [
    {"question" : "Que va faire l'air stable après qu'elle ait été forcé de monter?", "réponse" : "l'air va redessendre"},
    {"question" : "Que va faire l'air instable après qu'elle ait été forcé de monter?", "réponse" : "l'air va continuer de monter"},
    {"question" : "Que va faire l'air neutre après qu'elle ait été forcé de monter?", "réponse" : "l'air va rester à l'altitude où elle est"},
    {"question" : "Si une particule est au dessus du GTVM, va-t-elle monté, dessendre ou rester au même niveau?", "réponse" : "monté"},
    {"question" : "Si une particule est en dessous du GTVM, va-t-elle monté, dessendre ou rester au même niveau?", "réponse" : "dessendre"},
    {"question" : "Comment se nomme le type de stabilité lorsqu'une particule revient à son point de départ?", "réponse" : "stabilité absolue"},
    {"question" : "Si le GTVM change pour qu'il fasse plus froid à haut niveau et plus chaud à bas niveau, l'air devient-elle plus stable ou plus instable?", "réponse" : "instable"},
    {"question" : "Si le GTVM change pour qu'il fasse plus chaud à haut niveau et plus froid à bas niveau, l'air devient-elle plus stable ou plus instable?", "réponse" : "stable"},
    {"question" : "Quels sont les cinq éléments qui caractérise l'air stable?", "réponse" : "visibilité mauvaise, nuage stagnant, précipitation faible ou modéré, vent constant et faible ou modérer et continue et turbulence nul à léger"},
    {"question" : "Quels sont les cinq éléments qui caractérise l'air insatble?", "réponse" : "visibilité va s'améliorer, nuages vont bouger et nuage cumuliforme, précipitation en averse et avec des changements d'intensités, vent qui vont variés, jusqu'à fort, avec rafales et beaucoup de turbulence au niveau horizontale"},
]

pression_atmo = [
    {"question" : "La pression est responsable de 3 éléments. Quels sont-ils?", "réponse" : "altitude de vol, déplacement des système météorologique et perfromance de vol"},
    {"question" : "Quel élément influence le poid de la colonne d'air", "réponse" : "température"},
    {"question" : "Quel est l'interval de temps retenue pour calculer la pression théorique en dessous de la station, jusqu'au niveau de la mer?", "réponse" : "12 heures"},
    {"question" : "Quel est l'interval entre les lignes des isobares", "réponse" : "4 hPa"},
    {"question" : "Quel est la ligne d'isobare qui est toujours indiqué?", "réponse" : "1000 hPa"},
    {"question" : "Quels sont les autres noms de la basse pression", "réponse" : "dépression et cyclone"},
    {"question" : "Comment définit-on une zone de basse pression?", "réponse" : "une zone entouré de tous les côtés par une pression supérieur"},
    {"question" : "Si de l'air humide est dans une basse pression, que va-t-il se passer", "réponse" : "l'air va se condenser et former des nuages"},
    {"question" : "Quels sont les autres noms de la haute pression", "réponse" : "anti-cyclone"},
    {"question" : "Comment définit-on une zone de haute pression?", "réponse" : "une zone entouré de tous les côtés par une pression inférieure"},
    {"question" : "Quel temps fera-t-il dans une zone de haute pression et pourquoi?", "réponse" : "du beau temps, car l'air va dessendre et se réchauffer par compression, donc l'air va s'éloigner du point de rosé"},
    {"question" : "Qu'est ce qu'un creux barométrique?", "réponse" : "une zone allongée de basse pression où la pression la plus basse se trouve"},
    {"question" : "Comment sera la météo dans un creux barométrique et pourquoi?", "réponse" : "mauvaise, car c'est un zone de convergence"},
    {"question" : "Comment est identifié un creux barométrique?", "réponse" : "un trait"},
    {"question" : "Qu'est ce qu'une crête?", "réponse" : "une zone allongée de haute pression où la pression la plus forte se retrouve"},
    {"question" : "Comment sera la météo dans une crête et pourquoi?", "réponse" : "bonne, car c'est une haute pression"},
    {"question" : "Est-ce qu'une crête sera identifié?", "réponse" : "non"},
    {"question" : "Qu'est ce qu'un col?", "réponse" : "une zone neutre entre deux zones de hautes pression et deux zones de basses pression"},
    {"question" : "Qu'est ce que la tendence barométrique?", "réponse" : "la variation de la pression à un point donné en fonction du temps"},
    {"question" : "Plus les isobares sont collées, plus le vent sera ____.", "réponse" : "fort"},
    {"question" : "Où la force de coriolis sera-t-elle la plus forte?", "réponse" : "aux pôles"},
    {"question" : "Dans quel sens la force de coriolis influence-t-elle le vent?", "réponse" : "vers la droite"},
    {"question" : "Qu'est ce que le vent géostrophique et décris son mouvement?", "réponse" : "du vent où la force de coriolis, qui fait tourné le vent à droite, et la force de la haute pression, qui pousse l'air vers l'extérieur, ou la force de la basse pression, qui tire le vent vers l'intérieur. il est paralèlle aux isobares"},
    {"question" : "L'effet coriolis influence-t-il plus le vent en altitude ou au sol?", "réponse" : "sol"},
    {"question" : "Qu'est ce que la règle de Buys-Ballot?", "réponse" : "avec le vent dans le dos, la basse pression est à gauche"},
    {"question" : "Dans quel sens le vent tourne-t-il dans une zone de haute pression?", "réponse" : "horaire"},
    {"question" : "Dans quel sens le vent tourne-t-il dans une zone de basse pression?", "réponse" : "anti-horaire"},
    {"question" : "Le vent est-il plus fort dans la haute ou dans la basse pression à pression égale et pourquoi?", "réponse" : "haute pression, car il est aidé par la force centrifuge"},
    {"question" : "De combien de degrés le vent est-il dévié sur un terrain lisse?", "réponse" : "10"},
    {"question" : "De combien de degrés le vent est-il dévié sur un terrain accidenté?", "réponse" : "40"},
    {"question" : "Dans quel sens le vent est-il dévié à cause du sol?", "réponse" : "gauche"},
    {"question" : "Comment se nomme les vents qui augmente d'intensité qui tendent vers la droites en montant en altitude?", "réponse" : "dextrogyre"},
    {"question" : "Comment se nomme les vents qui diminue d'intensité qui tendent vers la gauche en dessendant en altitude?", "réponse" : "lévogyre"},
    {"question" : "Comment va se comporté les vents si le système s'intensifie?", "réponse" : "ils vont traversé les isobares"},
    {"question" : "Qu'est ce que l'altitude indiquée?", "réponse" : "l'altitude lue sur l'altimètre lorsqu'il est au calage de l'aéroport"},
    {"question" : "Qu'est ce que l'altitude pression?", "réponse" : "l'altitude lue sur l'altimètre lorsqu'il est au calage standard"},
    {"question" : "Qu'est ce que l'altitude densité?", "réponse" : "l'altitude pression corrigée pour les erreurs de température"},
    {"question" : "Qu'est ce que l'altitude vraie?", "réponse" : "l'altitude réelle par rapport au niveau de la mer"},
    {"question" : "Qu'est ce que la hauteur?", "réponse" : "l'élévation réelle au dessus du sol"},
    {"question" : "Qu'est ce que le niveau de vol?", "réponse" : "l'altitude en centaine de pieds lorsqu'on utilise le calage standard"},
]

masse_air = [
    {"question" : "Quelles sont les caractèristiques de l'atmosphère?", "réponse" : "humidité, température, stabilité, altitude de la tropopause"},
    {"question" : "Quel est la définition d'une masse d'air?", "réponse" : "un grand volume d'air ayant acquis les mêmes caractéristique"},
    {"question" : "Quel est la limite verticale d'une masse d'air?", "réponse" : "la tropopause"},
    {"question" : "Qu'est ce qu'une masse d'air mA?", "réponse" : "maritime arctique"},
    {"question" : "Qu'est ce qu'une masse d'air cA?", "réponse" : "continentale arctique"},
    {"question" : "Qu'est ce qu'une masse d'air mP?", "réponse" : "maritime polaire"},
    {"question" : "Qu'est ce qu'une masse d'air cP?", "réponse" : "continentale polaire"},
    {"question" : "Qu'est ce qu'une masse d'air mT?", "réponse" : "maritime tropicale"},
    {"question" : "Qu'est ce qu'une masse d'air cT?", "réponse" : "continentale tropicale"},
    {"question" : "Quels sont les masses d'air qui touchent le Canada (abréviation)?", "réponse" : "ca, ma, mp, mt"},
    {"question" : "Si l'air est froid, la tropopause est-elle haute ou basse?", "réponse" : "haute"},
    {"question" : "Quels sont les trois caractéristiques qui influence le déplacement et le degré de changement d'une masse d'air?", "réponse" : "la vitesse de déplacement, l'humidité et la différence de température"},
    {"question" : "Quel phénomène sera créé par un réchauffement par le dessous?", "réponse" : "convection"},
    {"question" : "Quel phénomène sera créé par un reffroidissement par le dessous?", "réponse" : "inversion"},
    {"question" : "Comment se nomme la zone de transition entre deux masses d'air?", "réponse" : "un front"},
    {"question" : "Comment se nomme le front lorsque l'air froid s'en va?", "réponse" : "front chaud"},
    {"question" : "Comment se nomme le front lorsque l'air froid arrive?", "réponse" : "front froid"},
]

fronts = [
    {"question" : "Quel est la largeur de la zone de mélange d'un front?", "réponse" : "50 à 100 nm"},
    {"question" : "Dans quel système se retouve presque tous les fronts?", "réponse" : "basse pression"},
    {"question" : "De quel masse d'air provient le nom du front?", "réponse" : "l'air froid"},
    {"question" : "Quels sont les quatres éléments requis pour qu'un front soit indiqué sur une carte?", "réponse" : "changement de vent, de température, d'humidité et de pression"},
    {"question" : "Si un front se déplace perpendiculairement aux isobares, ira-t-il plus vite qu'un front qui se déplace paralèllement aux isobares?", "réponse" : "oui"},
    {"question" : "Quel front va le plus vite?", "réponse" : "front froid"},
    {"question" : "Comment se nomme le phénomène lorsque l'air chaud glisse sur l'air froid et monte en altitude?", "réponse" : "glissement ascendant frontale"},
    {"question" : "Quels sont les rapports de pente du front chaud?", "réponse" : "1 pour 150 à 1 pour 200"},
    {"question" : "Quel est le rapport de pente du front froid?", "réponse" : "1 pour 50"},
    {"question" : "Pour qu'une ligne de grain se forme, faut-il que le front froid soit rapide ou lent?", "réponse" : "rapide"},
    {"question" : "Qu'est ce qui crée des fronts en altitude?", "réponse" : "des montagnes, un changement trop faible pour être qualifier de front au sol ou une réchauffement du sol par le soleil"},
    {"question" : "Généralement, va-t-on renconter des phénomènes avant ou après le changement de température avec un front en altitude?", "réponse" : "avant"},
    {"question" : "La différence entre les masses d'air est-elle plus importante au sol ou en altitude et qu'elle est l'altitude qui définit la partie basse de la partie haute (pour cette question uniquqment)?", "réponse" : "au sol, en dessous de 4000 pi"},
    {"question" : "Quels sont les cinq caractéristiques qui vont changer lors du passage d'un front?", "réponse" : "la température, le point de rosée, la pression, le vent et la visibilité"},
    {"question" : "Lors du passage d'un front, la température va-t-elle changer brusquement ou graduellement?", "réponse" : "brusquement"},
    {"question" : "Lors du passage d'un front chaud, est-ce que le point de rosé va augmenter?", "réponse" : "oui"},
    {"question" : "Lors du passage d'un front chaud, comment varie la pression?", "réponse" : "elle diminue"},
    {"question" : "Lors du passage d'un front froid, comment varie la pression?", "réponse" : "elle augmente"},
    {"question" : "Où se trouve les fronts dans une basse pression?", "réponse" : "dans les creux"},
    {"question" : "Le vent va-t-il plus vite dans l'air froid ou dans l'air chaud?", "réponse" : "froid"},
    {"question" : "Dans quel direction faut-il corriger notre cap lorsqu'on passe un front?", "réponse" : "à droite"},
    {"question" : "Lors du passage d'un front froid, comment varie la visibilité?", "réponse" : "augmente"},
    {"question" : "Lors du passage d'un front chaud, comment varie la visibilité?", "réponse" : "diminue"},
    {"question" : "Qu'est-ce qu'une occlusion et comment sera le temp?", "réponse" : "un front froid qui ratrappe un front chaud et qui se combinent ensemble. le temps dépendra de l'addition des deux fronts et sera plus intense à l'endroit où les deux fronts se rencontre"},
]

nuage_precipitation = [
    {"question" : "Quels sont les éléments requis pour qu'il y ait des nuages?", "réponse" : "humidité, noyeau de condensation et processus de refroidissement"},
    {"question" : "Quels sont le(s) altitude(s) qui définissent les nuages élevés?", "réponse" : "20 000 à 40 000 pi"},
    {"question" : "Quels sont le(s) altitude(s) qui définissent les nuages moyens?", "réponse" : "6500 à 20 000 pi"},
    {"question" : "Quels sont le(s) altitude(s) qui définissent les nuages bas?", "réponse" : "6500 pi et moins"},
    {"question" : "Quels sont le(s) altitude(s) qui définissent les nuages à developpement verticale?", "réponse" : "base à partir de 1600 pi"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage ST?", "réponse" : "stratus, bas, ressemble au brouillard, air stable, ne repose pas au sol, bruine ou failble neige"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage NS?", "réponse" : "nimbostratus, bas, précipitation continue faible ou modérée, très épais, air stable"},
    {"question" : "Quel est l'épaisseur du NS?", "réponse" : "5000 à 15 000 pi d'épaisseur"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage SC?", "réponse" : "stratocumulus, bas, base bien définit, ondulé ou roulé, peu de précipitation"},
    {"question" : "Que se passe-t-il avec l'air lorsque le nuage est ondulé ou roulé?", "réponse" : "l'air est instable en dessous, stable au dessus et il y a de la turbulence mécanique"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage AS?", "réponse" : "altostratus, moyen, on peut voir la lune ou le soleil au travers, donc il n'est pas très épais"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage AC?", "réponse" : "altocumulus, moyen, instabilité au dessus du nuage"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage ACC?", "réponse" : "altocumulus castellanus, moyen, ressemble à ac, tourelle bien défini, très instable"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CI?", "réponse" : "cirus, élevé, cheveux d'ange"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CS?", "réponse" : "cirrostratus, élevé, halo autour des astres, humidité visible, givrage possible, dangereux"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CC?", "réponse" : "cirrocumulus, élevé, présence d'instabilité"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CU?", "réponse" : "cumulus, développement verticale, turbulence mécanique et instabilité, beau temps, base bien définie, cumulus fractus quand ils se séparent"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage TCU?", "réponse" : "cumulus bourgeonnant ou cumulus congestus, développement verticale, aspect de chou-fleur, givrage fort, vent ascendent et dessendent, précipitation"},
    {"question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CB?", "réponse" : "cumulonimbus, développement verticale, orages, cisaillement du vent à bas niveau, forme d'enclume"},
    {"question" : "Pourquoi le CB a-t-il une forme d'enclume?", "réponse" : "il y a une inversion à la tropopause"},
    {"question" : "La partie la plus longue de l'enclume indique quoi et où est-elle par rapport au CB?", "réponse" : "la direction dans laquelle le cb va et elle est en avant du cb."},
    {"question" : "Comment se nomme le principe lorsque de l'air froid arrive au dessus d'une étendu chaude et humide et que l'air se charge d'humidité et se condense?", "réponse" : "convection due à l'advection"},
    {"question" : "Que se passe-t-il à la base des nuages lorsqu'il y a de la convection?", "réponse" : "La base du nuage va monté, car le bas du nuage va s'évaporé"},
    {"question" : "Où va se situer la turbulence mécanique par rapport au nuage?", "réponse" : "en dessous ou dans le nuage"},
    {"question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaitre les nuages pour un front chaud, humide et stable?", "réponse" : "ci, cs, as, ns et st"},
    {"question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaitre les nuages pour un front chaud, humide et instable?", "réponse" : "ci, cs, ac et as et cb et ct, cb et ns"},
    {"question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaitre les nuages pour un front chaud, sec et stable?", "réponse" : "ci, cs, as"},
    {"question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaitre les nuages pour un front froid, instable, humide et chaud?", "réponse" : "st, cb, cu"},
    {"question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaitre les nuages pour un front froid, peut-être instable, humide et chaud?", "réponse" : "tcu, ac et as, tcu, cs et ci, cu"},
    {"question" : "Quels sont les nuages associées au lignes de grain et comment sont-ils?", "réponse" : "cb et tcu organisés"},
    {"question" : "Quels sont les éléments qui influencent les changements lors d'un soulèvement orographique?", "réponse" : "vitesse du déplacement, élévation du terrain, humidité"},
    {"question" : "De quel élément dépend le type de nuage lors d'un soulèvement orographique?", "réponse" : "la stabilité de l'air"},
    {"question" : "Qu'est ce qu'une cuvette d'air froid?", "réponse" : "lorsque l'air stagne, car elle n'a pas assez d'énergie pour passer au dessus d'une montagne, mais se refroidit"},
    {"question" : "Est-ce que la convergence va ammené un soulèvement rapide ou lent?", "réponse" : "lent"},
    {"question" : "L'advection est-elle plus importante lors du réchauffement ou du refroidissement pour la formation des nuages?", "réponse" : "refroidissement"},
    {"question" : "Comment les précipitaions vont influencer les nuages?", "réponse" : "une partie des goutelette va s'évaporer, ce qui va créer des stratus en altitude ou du brouillard ou de la brume au sol"},
    {"question" : "Quel est l'élément responsable de la pluie?", "réponse" : "les courants verticaux"},
    {"question" : "Pourquoi les courants verticaux sont-ils responsable des précipitations?", "réponse" : "les goutelette vont bouger, donc se cogner et grossir"},
    {"question" : "Qu'est ce que l'effet Bergeron?", "réponse" : "la saturation autour d'un cristal de glace se fait à un taux d'humidité plus bas qu'une goutelette. donc, il refroidit se qui est autour de lui, grossit, devient plus lourd, dessend et inci de suite. il ne devient jamais très gros et deveient de la pluie s'il passe dans une zone d'air chaud"},
    {"question" : "Que fait l'effet de coalescence ou de captation?", "réponse" : "il provoque un accroissement rapide de la dimension donc de leur masse et de leur vitesse de chute."},
    {"question" : "Que se passe-t-il lorsque deux critaux entre en collisions (lors de la formation des précipitations)?", "réponse" : "plusieurs fins cristaux se séparent et crés des nouveaux noyaux de condensation"},
    {"question" : "Qu'elle sera le type de précipitation s'il y a de l'air chaud au dessus d'air froid?", "réponse" : "précipitations verglaçante ou verglas"},
    {"question" : "Quels éléments influencent les précipitations?", "réponse" : "force du courant ascendant, humidité et température de l'air"},
    {"question" : "Que signifie averse?", "réponse" : "précipitation de courte durée, avec possibilité d'éclaircissement entre les précipitations et nuage cumuliforme"},
    {"question" : "Que signifie précipitation intermittente?", "réponse" : "pas une averse, mais précipitaions s'arrêtent et reprennent au moins une fois dans l'heure, nuage stratiforme, précipitations proviennent du même nuage"},
    {"question" : "Que signife précipitation continue?", "réponse" : "précipitation qui tombe sans intéruptions pendant au moins une heure, nuage stratiforme"},
    {"question" : "Quels sont les effets sur le vol des précipitations?", "réponse" : "possibilité de givrage, visibilité réduite, modifie l'écoulement de l'air sur l'aile, modifie la vitesse de décrochage, diminue le contact avec la piste"},
]