#   Ceci est un code pour créer une ia qui propose des recommandation basé sur les bonnes ou mauvaise réponse d'un questionnaire
#   Pour le cours de philo 2 Cchic
#   Questions basées sur les notes de cours personnelles de météo 1 du CQFA
#
#   Olivier Moreau
#

import streamlit as st

bqhumidité = [
    {"theme" : "humidite", "question" : "Exam 1 Quel est l'élément le plus important en météo?", "réponse" : "la vapeur d'eau"},
    {"theme" : "humidite", "question" : "Exam 1 Le point de rosée augmente si l'air est...", "réponse" : "chaud"},
    {"theme" : "humidite", "question" : "Exam 1 Qu'est-ce que le point de rosée?", "réponse" : "La température à pression constante à laquelle si l'air doit être refroidi pour qu'il y ait saturation"},
    {"theme" : "humidite", "question" : "Exam 1 Que fait l'eau lorsqu'elle est dans l'air et devient liquide?", "réponse" : "elle donne son énergie à l'air, ce qui augmente la température de l'air"},
]

bqréchauffement = [
    {"theme" : "rechauffement", "question" : "Exam 1 Quel est la température qui définit la tropopause?", "réponse" : "-56"},
    {"theme" : "rechauffement", "question" : "Exam 1 Quels sont les quatre couches de l'atmosphère?", "réponse" : "la troposphère, la mésosphère, la stratosphère et la thermosphère"},
    {"theme" : "rechauffement", "question" : "Exam 1 Quel type d'onde nous envoie le Soleil (2 lettres) et quel est sa longueur d'onde?", "réponse" : "uv et petite ou courte"},
    {"theme" : "rechauffement", "question" : "Exam 1 Qu'est-ce que la réflexion Albédo?", "réponse" : "Lorsque les rayons touchent la Terre perpendiculairement, ils sont plus puissants que ceux tangents"},
]

bqrefroidissement = [
    {"theme" : "refroidissement", "question" : "Exam 1 Comment ce nomme le concept qui définit que la température diminue de 1,98°C par 1000 pi?", "réponse" : "le gradient thermique vertical"},
    {"theme" : "refroidissement", "question" : "Exam 1 Comment ce nomme le concept qui définit que la température diminue de 3°C par 1000 pi?", "réponse" : "le gradient adiabatique sec"},
]

stabilite_air = [
    {"theme" : "stabilite", "question" : "Que va faire l'air stable après qu'il ait été forcée de monter?", "réponse" : "l'air va redescendre"},
    {"theme" : "stabilite", "question" : "Que va faire l'air instable après qu'il ait été forcée de monter?", "réponse" : "l'air va continuer de monter"},
    {"theme" : "stabilite", "question" : "Que va faire l'air neutre après qu'elle ait été forcée de monter?", "réponse" : "l'air va rester à l'altitude où il est"},
    {"theme" : "stabilite", "question" : "Si une particule est au dessus du GTVM, va-t-elle monter, descendre ou rester au même niveau?", "réponse" : "monter"},
    {"theme" : "stabilite", "question" : "Si une particule est en dessous du GTVM, va-t-elle monter, descendre ou rester au même niveau?", "réponse" : "descendre"},
    {"theme" : "stabilite", "question" : "Comment se nomme le type de stabilité lorsqu'une particule revient à son point de départ?", "réponse" : "stabilité absolue"},
    {"theme" : "stabilite", "question" : "Si le GTVM change pour qu'il fasse plus froid à haut niveau et plus chaud à bas niveau, l'air devient-il plus stable ou plus instable?", "réponse" : "instable"},
    {"theme" : "stabilite", "question" : "Si le GTVM change pour qu'il fasse plus chaud à haut niveau et plus froid à bas niveau, l'air devient-il plus stable ou plus instable?", "réponse" : "stable"},
    {"theme" : "stabilite", "question" : "Quels sont les cinq éléments qui caractérisent l'air stable?", "réponse" : "visibilité mauvaise, nuages stagnants, précipitation faible ou modérée, vent constant et faible ou modéré et continue et turbulence nulle à léger"},
    {"theme" : "stabilite", "question" : "Quels sont les cinq éléments qui caractérisent l'air instable?", "réponse" : "visibilité va s'améliorer, nuages vont bouger et nuage cumuliforme, précipitation en averse et avec des changements d'intensités, vents qui vont varier, jusqu'à fort, avec rafales et beaucoup de turbulence au niveau horizontal"},
]

pression_atmo = [
    {"theme" : "pression", "question" : "La pression est responsable de 3 éléments. Quels sont-ils?", "réponse" : "altitude de vol, déplacement des systèmes météorologiques et performance de vol"},
    {"theme" : "pression", "question" : "Quel élément influence le poids de la colonne d'air", "réponse" : "température"},
    {"theme" : "pression", "question" : "Quel est l'intervalle de temps retenu pour calculer la pression théorique en dessous de la station, jusqu'au niveau de la mer?", "réponse" : "12 heures"},
    {"theme" : "pression", "question" : "Quel est l'intervalle entre les lignes des isobares", "réponse" : "4 hPa"},
    {"theme" : "pression", "question" : "Quel est la ligne d'isobare qui est toujours indiquée?", "réponse" : "1000 hPa"},
    {"theme" : "pression", "question" : "Quels sont les autres noms de la basse pression", "réponse" : "dépression et cyclone"},
    {"theme" : "pression", "question" : "Comment définit-on une zone de basse pression?", "réponse" : "une zone entourée de tous les côtés par une pression supérieure"},
    {"theme" : "pression", "question" : "Si de l'air humide est dans une basse pression, que va-t-il se passer", "réponse" : "l'air va se condenser et former des nuages"},
    {"theme" : "pression", "question" : "Quels sont les autres noms de la haute pression", "réponse" : "anticyclone"},
    {"theme" : "pression", "question" : "Comment définit-on une zone de haute pression?", "réponse" : "une zone entourée de tous les côtés par une pression inférieure"},
    {"theme" : "pression", "question" : "Quel temps fera-t-il dans une zone de haute pression et pourquoi?", "réponse" : "du beau temps, car l'air va descendre et se réchauffer par compression, donc l'air va s'éloigner du point de rosée"},
    {"theme" : "pression", "question" : "Qu'est-ce qu'un creux barométrique?", "réponse" : "une zone allongée de basse pression où la pression la plus basse se trouve"},
    {"theme" : "pression", "question" : "Comment sera la météo dans un creux barométrique et pourquoi?", "réponse" : "mauvaise, car c'est un zone de convergence"},
    {"theme" : "pression", "question" : "Comment est identifié un creux barométrique?", "réponse" : "un trait"},
    {"theme" : "pression", "question" : "Qu'est-ce qu'une crête?", "réponse" : "une zone allongée de haute pression où la pression la plus forte se retrouve"},
    {"theme" : "pression", "question" : "Comment sera la météo dans une crête et pourquoi?", "réponse" : "bonne, car c'est une haute pression"},
    {"theme" : "pression", "question" : "Est-ce qu'une crête sera identifié?", "réponse" : "non"},
    {"theme" : "pression", "question" : "Qu'est-ce qu'un col?", "réponse" : "une zone neutre entre deux zones de hautes pression et deux zones de basses pression"},
    {"theme" : "pression", "question" : "Qu'est-ce que la tendance barométrique?", "réponse" : "la variation de la pression à un point donné en fonction du temps"},
    {"theme" : "pression", "question" : "Plus les isobares sont collées, plus le vent sera ____.", "réponse" : "fort"},
    {"theme" : "pression", "question" : "Où la force de coriolis sera-t-elle la plus forte?", "réponse" : "aux pôles"},
    {"theme" : "pression", "question" : "Dans quel sens la force de coriolis influence-t-elle le vent?", "réponse" : "vers la droite"},
    {"theme" : "pression", "question" : "Qu'est-ce que le vent géostrophique et décris son mouvement?", "réponse" : "du vent où la force de coriolis, qui fait tourner le vent à droite, et la force de la haute pression, qui pousse l'air vers l'extérieur, ou la force de la basse pression, qui tire le vent vers l'intérieur, est égale. il est parallèle aux isobares"},
    {"theme" : "pression", "question" : "L'effet coriolis influence-t-il plus le vent en altitude ou au sol?", "réponse" : "en altitude"},
    {"theme" : "pression", "question" : "Qu'est-ce que la règle de Buys-Ballot?", "réponse" : "avec le vent dans le dos, la basse pression est à gauche"},
    {"theme" : "pression", "question" : "Dans quel sens le vent tourne-t-il dans une zone de haute pression?", "réponse" : "horaire"},
    {"theme" : "pression", "question" : "Dans quel sens le vent tourne-t-il dans une zone de basse pression?", "réponse" : "antihoraire"},
    {"theme" : "pression", "question" : "Le vent est-il plus fort dans la haute ou dans la basse pression à pression égale et pourquoi?", "réponse" : "haute pression, car il est aidé par la force centrifuge"},
    {"theme" : "pression", "question" : "De combien de degrés le vent est-il dévié sur un terrain lisse?", "réponse" : "10"},
    {"theme" : "pression", "question" : "De combien de degrés le vent est-il dévié sur un terrain accidenté?", "réponse" : "40"},
    {"theme" : "pression", "question" : "Dans quel sens le vent est-il dévié à cause du sol?", "réponse" : "gauche"},
    {"theme" : "pression", "question" : "Comment se nomme les vents qui augmente d'intensité qui tendent vers la droite en montant en altitude?", "réponse" : "dextrogyre"},
    {"theme" : "pression", "question" : "Comment se nomme les vents qui diminuent d'intensité qui tendent vers la gauche en descendant en altitude?", "réponse" : "lévogyre"},
    {"theme" : "pression", "question" : "Comment va se comporter les vents si le système s'intensifie?", "réponse" : "ils vont traverser les isobares"},
    {"theme" : "pression", "question" : "Qu'est-ce que l'altitude indiquée?", "réponse" : "l'altitude lue sur l'altimètre lorsqu'il est au calage de l'aéroport"},
    {"theme" : "pression", "question" : "Qu'est-ce que l'altitude pression?", "réponse" : "l'altitude lue sur l'altimètre lorsqu'il est au calage standard"},
    {"theme" : "pression", "question" : "Qu'est-ce que l'altitude densité?", "réponse" : "l'altitude pression corrigée pour les erreurs de température"},
    {"theme" : "pression", "question" : "Qu'est-ce que l'altitude vraie?", "réponse" : "l'altitude réelle par rapport au niveau de la mer"},
    {"theme" : "pression", "question" : "Qu'est-ce que la hauteur?", "réponse" : "l'élévation réelle au dessus du sol"},
    {"theme" : "pression", "question" : "Qu'est-ce que le niveau de vol?", "réponse" : "l'altitude en centaines de pieds lorsqu'on utilise le calage standard"},
]

masse_air = [
    {"theme" : "masse", "question" : "Quelles sont les caractéristiques de l'atmosphère?", "réponse" : "humidité, température, stabilité, altitude de la tropopause"},
    {"theme" : "masse", "question" : "Quel est la définition d'une masse d'air?", "réponse" : "un grand volume d'air ayant acquis les mêmes caractéristiques"},
    {"theme" : "masse", "question" : "Quel est la limite verticale d'une masse d'air?", "réponse" : "la tropopause"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air mA?", "réponse" : "maritime arctique"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air cA?", "réponse" : "continentale arctique"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air mP?", "réponse" : "maritime polaire"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air cP?", "réponse" : "continentale polaire"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air mT?", "réponse" : "maritime tropicale"},
    {"theme" : "masse", "question" : "Qu'est-ce qu'une masse d'air cT?", "réponse" : "continentale tropicale"},
    {"theme" : "masse", "question" : "Quels sont les masses d'air qui touchent le Canada (abréviation)?", "réponse" : "ca, ma, mp, mt"},
    {"theme" : "masse", "question" : "Si l'air est froid, la tropopause est-elle haute ou basse?", "réponse" : "haute"},
    {"theme" : "masse", "question" : "Quels sont les trois caractéristiques qui influence le déplacement et le degré de changement d'une masse d'air?", "réponse" : "la vitesse de déplacement, l'humidité et la différence de température"},
    {"theme" : "masse", "question" : "Quel phénomène sera créé par un réchauffement par le dessous?", "réponse" : "convection"},
    {"theme" : "masse", "question" : "Quel phénomène sera créé par un refroidissement par le dessous?", "réponse" : "inversion"},
    {"theme" : "masse", "question" : "Comment se nomme la zone de transition entre deux masses d'air?", "réponse" : "un front"},
    {"theme" : "masse", "question" : "Comment se nomme le front lorsque l'air froid s'en va?", "réponse" : "front chaud"},
    {"theme" : "masse", "question" : "Comment se nomme le front lorsque l'air froid arrive?", "réponse" : "front froid"},
]

fronts = [
    {"theme" : "front", "question" : "Quel est la largeur de la zone de mélange d'un front?", "réponse" : "50 à 100 nm"},
    {"theme" : "front", "question" : "Dans quel système se retrouve presque tous les fronts?", "réponse" : "basse pression"},
    {"theme" : "front", "question" : "De quel masse d'air provient le nom du front?", "réponse" : "l'air froid"},
    {"theme" : "front", "question" : "Quels sont les quatre éléments requis pour qu'un front soit indiqué sur une carte?", "réponse" : "changement de vent, de température, d'humidité et de pression"},
    {"theme" : "front", "question" : "Si un front se déplace perpendiculairement aux isobares, ira-t-il plus vite qu'un front qui se déplace parallèlement aux isobares?", "réponse" : "oui"},
    {"theme" : "front", "question" : "Quel front va le plus vite?", "réponse" : "front froid"},
    {"theme" : "front", "question" : "Comment se nomme le phénomène lorsque l'air chaud glisse sur l'air froid et monte en altitude?", "réponse" : "glissement ascendant frontal"},
    {"theme" : "front", "question" : "Quels sont les rapports de pente du front chaud?", "réponse" : "1 pour 150 à 1 pour 200"},
    {"theme" : "front", "question" : "Quel est le rapport de pente du front froid?", "réponse" : "1 pour 50"},
    {"theme" : "front", "question" : "Pour qu'une ligne de grain se forme, faut-il que le front froid soit rapide ou lent?", "réponse" : "rapide"},
    {"theme" : "front", "question" : "Qu'est-ce qui crée des fronts en altitude?", "réponse" : "des montagnes, un changement trop faible pour être qualifié de front au sol ou une réchauffement du sol par le soleil"},
    {"theme" : "front", "question" : "Généralement, va-t-on rencontrer des phénomènes avant ou après le changement de température avec un front en altitude?", "réponse" : "avant"},
    {"theme" : "front", "question" : "La différence entre les masses d'air est-elle plus importante au sol ou en altitude et quelle est l'altitude qui définit la partie basse de la partie haute (pour cette question uniquqment)?", "réponse" : "au sol, en dessous de 4000 pi"},
    {"theme" : "front", "question" : "Quels sont les cinq caractéristiques qui vont changer lors du passage d'un front?", "réponse" : "la température, le point de rosée, la pression, le vent et la visibilité"},
    {"theme" : "front", "question" : "Lors du passage d'un front, la température va-t-elle changer brusquement ou graduellement?", "réponse" : "brusquement"},
    {"theme" : "front", "question" : "Lors du passage d'un front chaud, est-ce que le point de rosée va augmenter?", "réponse" : "oui"},
    {"theme" : "front", "question" : "Lors du passage d'un front chaud, comment varie la pression?", "réponse" : "elle diminue"},
    {"theme" : "front", "question" : "Lors du passage d'un front froid, comment varie la pression?", "réponse" : "elle augmente"},
    {"theme" : "front", "question" : "Où se trouve les fronts dans une basse pression?", "réponse" : "dans les creux"},
    {"theme" : "front", "question" : "Le vent va-t-il plus vite dans l'air froid ou dans l'air chaud?", "réponse" : "froid"},
    {"theme" : "front", "question" : "Dans quel direction faut-il corriger notre cap lorsqu'on passe un front?", "réponse" : "à droite"},
    {"theme" : "front", "question" : "Lors du passage d'un front froid, comment varie la visibilité?", "réponse" : "augmente"},
    {"theme" : "front", "question" : "Lors du passage d'un front chaud, comment varie la visibilité?", "réponse" : "diminue"},
    {"theme" : "front", "question" : "Qu'est-ce qu'une occlusion et comment sera le temps?", "réponse" : "un front froid qui rattrappe un front chaud et qui se combinent ensemble. le temps dépendra de l'addition des deux fronts et sera plus intense à l'endroit où les deux fronts se rencontrent"},
]

nuage_precipitation = [
    {"theme" : "nuage", "question" : "Quels sont les éléments requis pour qu'il y ait des nuages?", "réponse" : "humidité, noyau de condensation et processus de refroidissement"},
    {"theme" : "nuage", "question" : "Quels sont le(s) altitude(s) qui définissent les nuages élevés?", "réponse" : "20 000 à 40 000 pi"},
    {"theme" : "nuage", "question" : "Quels sont le(s) altitude(s) qui définissent les nuages moyens?", "réponse" : "6500 à 20 000 pi"},
    {"theme" : "nuage", "question" : "Quels sont le(s) altitude(s) qui définissent les nuages bas?", "réponse" : "6500 pi et moins"},
    {"theme" : "nuage", "question" : "Quels sont le(s) altitude(s) qui définissent les nuages à développement vertical?", "réponse" : "base à partir de 1600 pi"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage ST?", "réponse" : "stratus, bas, ressemble au brouillard, air stable, ne repose pas au sol, bruine ou faible neige"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage NS?", "réponse" : "nimbostratus, bas, précipitation continue faible ou modérée, très épais, air stable"},
    {"theme" : "nuage", "question" : "Quel est l'épaisseur du NS?", "réponse" : "5000 à 15 000 pi d'épaisseur"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage SC?", "réponse" : "stratocumulus, bas, base bien définie, ondulé ou roulé, peu de précipitation"},
    {"theme" : "nuage", "question" : "Que se passe-t-il avec l'air lorsque le nuage est ondulé ou roulé?", "réponse" : "l'air est instable en dessous, stable au dessus et il y a de la turbulence mécanique"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage AS?", "réponse" : "altostratus, moyen, on peut voir la lune ou le soleil au travers, donc il n'est pas très épais"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage AC?", "réponse" : "altocumulus, moyen, instabilité au dessus du nuage"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage ACC?", "réponse" : "altocumulus castellanus, moyen, ressemble à ac, tourelle bien défini, très instable"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CI?", "réponse" : "cirrus, élevé, cheveux d'ange"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CS?", "réponse" : "cirrostratus, élevé, halo autour des astres, humidité visible, givrage possible, dangereux"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CC?", "réponse" : "cirrocumulus, élevé, présence d'instabilité"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CU?", "réponse" : "cumulus, développement verticale, turbulence mécanique et instabilité, beau temps, base bien définie, cumulus fractus quand ils se séparent"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage TCU?", "réponse" : "cumulus bourgeonnant ou cumulus congestus, développement verticale, aspect de chou-fleur, givrage fort, vent ascendant et descendent, précipitation"},
    {"theme" : "nuage", "question" : "Quel est le nom, la hauteur et les caractéristiques du nuage CB?", "réponse" : "cumulonimbus, développement verticale, orages, cisaillement du vent à bas niveau, forme d'enclume"},
    {"theme" : "nuage", "question" : "Pourquoi le CB a-t-il une forme d'enclume?", "réponse" : "il y a une inversion à la tropopause"},
    {"theme" : "nuage", "question" : "La partie la plus longue de l'enclume indique quoi et où est-elle par rapport au CB?", "réponse" : "la direction dans laquelle le cb va et elle est en avant du cb."},
    {"theme" : "nuage", "question" : "Comment se nomme le principe lorsque de l'air froid arrive au dessus d'une étendue chaude et humide et que l'air se charge d'humidité et se condense?", "réponse" : "convection due à l'advection"},
    {"theme" : "nuage", "question" : "Que se passe-t-il à la base des nuages lorsqu'il y a de la convection?", "réponse" : "La base du nuage va monter, car le bas du nuage va s'évaporer"},
    {"theme" : "nuage", "question" : "Où va se situer la turbulence mécanique par rapport au nuage?", "réponse" : "en dessous ou dans le nuage"},
    {"theme" : "nuage", "question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaître les nuages pour un front chaud, humide et stable?", "réponse" : "ci, cs, as, ns et st"},
    {"theme" : "nuage", "question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaître les nuages pour un front chaud, humide et instable?", "réponse" : "ci, cs, ac et as et cb et ct, cb et ns"},
    {"theme" : "nuage", "question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaître les nuages pour un front chaud, sec et stable?", "réponse" : "ci, cs, as"},
    {"theme" : "nuage", "question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaître les nuages pour un front froid, instable, humide et chaud?", "réponse" : "st, cb, cu"},
    {"theme" : "nuage", "question" : "Dans quel ordre, avec les abréviations, allons nous voir apparaître les nuages pour un front froid, peut-être instable, humide et chaud?", "réponse" : "tcu, ac et as, tcu, cs et ci, cu"},
    {"theme" : "nuage", "question" : "Quels sont les nuages associées au lignes de grain et comment sont-ils?", "réponse" : "cb et tcu organisés"},
    {"theme" : "nuage", "question" : "Quels sont les éléments qui influencent les changements lors d'un soulèvement orographique?", "réponse" : "vitesse du déplacement, élévation du terrain, humidité"},
    {"theme" : "nuage", "question" : "De quel élément dépend le type de nuage lors d'un soulèvement orographique?", "réponse" : "la stabilité de l'air"},
    {"theme" : "nuage", "question" : "Qu'est-ce qu'une cuvette d'air froid?", "réponse" : "lorsque l'air stagne, car elle n'a pas assez d'énergie pour passer au dessus d'une montagne, mais se refroidit"},
    {"theme" : "nuage", "question" : "Est-ce que la convergence va amener un soulèvement rapide ou lent?", "réponse" : "lent"},
    {"theme" : "nuage", "question" : "L'advection est-elle plus importante lors du réchauffement ou du refroidissement pour la formation des nuages?", "réponse" : "refroidissement"},
    {"theme" : "nuage", "question" : "Comment les précipitations vont influencer les nuages?", "réponse" : "une partie des gouttelettes va s'évaporer, ce qui va créer des stratus en altitude ou du brouillard ou de la brume au sol"},
    {"theme" : "nuage", "question" : "Quel est l'élément responsable de la pluie?", "réponse" : "les courants verticaux"},
    {"theme" : "nuage", "question" : "Pourquoi les courants verticaux sont-ils responsables des précipitations?", "réponse" : "les gouttelettes vont bouger, donc se cogner et grossir"},
    {"theme" : "nuage", "question" : "Qu'est-ce que l'effet Bergeron?", "réponse" : "la saturation autour d'un cristal de glace se fait à un taux d'humidité plus bas qu'une gouttelette. donc, il refroidit se qui est autour de lui, grossit, devient plus lourd, descend et ainsi de suite. il ne devient jamais très gros et deviennent de la pluie s'il passe dans une zone d'air chaud"},
    {"theme" : "nuage", "question" : "Que fait l'effet de coalescence ou de captation?", "réponse" : "il provoque un accroissement rapide de la dimension donc de leur masse et de leur vitesse de chute."},
    {"theme" : "nuage", "question" : "Que se passe-t-il lorsque deux cristaux entrent en collisions (lors de la formation des précipitations)?", "réponse" : "plusieurs fins cristaux se séparent et créent des nouveaux noyaux de condensation"},
    {"theme" : "nuage", "question" : "Quelle sera le type de précipitation s'il y a de l'air chaud au dessus d'air froid?", "réponse" : "précipitations verglaçantes ou verglas"},
    {"theme" : "nuage", "question" : "Quels éléments influencent les précipitations?", "réponse" : "force du courant ascendant, humidité et température de l'air"},
    {"theme" : "nuage", "question" : "Que signifie averse?", "réponse" : "précipitation de courte durée, avec possibilité d'éclaircissement entre les précipitations et nuage cumuliforme"},
    {"theme" : "nuage", "question" : "Que signifie précipitation intermittente?", "réponse" : "pas une averse, mais précipitations s'arrêtent et reprennent au moins une fois dans l'heure, nuage stratiforme, précipitations proviennent du même nuage"},
    {"theme" : "nuage", "question" : "Que signifie précipitation continue?", "réponse" : "précipitation qui tombe sans intérruptions pendant au moins une heure, nuage stratiforme"},
    {"theme" : "nuage", "question" : "Quels sont les effets sur le vol des précipitations?", "réponse" : "possibilité de givrage, visibilité réduite, modifie l'écoulement de l'air sur l'aile, modifie la vitesse de décrochage, diminue le contact avec la piste"},
]

categorie = {
    "humidite" : bqhumidité,
    "rechauffement" : bqréchauffement,
    "refroidissement" : bqrefroidissement,
    "stabilite" : stabilite_air,
    "pression" : pression_atmo,
    "masse" : masse_air,
    "front" : fronts,
    "nuage" : nuage_precipitation
}